// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esopwshrwvdlvywpvxvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzb3B3c2hyd3ZkbHZ5d3B2eHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTkzMjgsImV4cCI6MjA2MzQzNTMyOH0.MmFc_kqy-aLD4s8TRXwDFHccGp37urwjdjCRYVtiXAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);